### ISSUE TITLE
Increase contrast on the last line of the screenshot in the README.md

### ISSUE THREAD

**Issue by moy** [Sarcasm/run-clang-format#10]
I do like the screenshot given in https://github.com/Sarcasm/run-clang-format/blob/master/screenshot.png, but there's at least [one instance of a user who didn't see the last line](https://stackoverflow.com/questions/22866609/can-clang-format-tell-me-if-formatting-changes-are-necessary/50872482?noredirect=1#comment98964097_50872482) because it's dark grey on black background. Increasing the contrast (i.e. use lighter grey) a little would help making the message fully self-explanatory.

**Comment by Sarcasm** [comment]
It's sad there was only the image, because the line just before the image says:

> A diff output is produced and a sensible exit code is returned.
> -- https://github.com/Sarcasm/run-clang-format/blob/49182c884a50b752c7fefe393df4067f1f877557/README.rst#introduction

https://github.com/Sarcasm/run-clang-format/blob/49182c884a50b752c7fefe393df4067f1f877557/README.rst#L16-L22

I will let you pick the color you think is the best, my personal preference is the middle one.
Please note that this is a feature of my ZSH theme, and I hope users won't assume it's an output of `run-clang-format.py`.

The current setting as a reference:

    $ zstyle ':zuko:autoreport:' text-color 239

![image](https://user-images.githubusercontent.com/424046/57892900-15797700-7841-11e9-8da8-91252ee21260.png)

    $ zstyle ':zuko:autoreport:' text-color 242

![image](https://user-images.githubusercontent.com/424046/57892931-45c11580-7841-11e9-9166-3d069b890d5f.png)

    $ zstyle ':zuko:autoreport:' text-color 245

![image](https://user-images.githubusercontent.com/424046/57892942-53769b00-7841-11e9-88fb-cec3975d1ff4.png)

**Comment by moy** [comment]
> It's sad there was only the image, because the line just before the image says:

Indeed, but I found the image so nice that I thought image + link to the home page were sufficient (but apparently clicking the link was too much effort ;-) ).

I have a preference for the last one, but the middle one is probably fine too.

Thanks for the quick reply.

**Comment by Sarcasm** [comment]
It's up, I picked up the last one.
I hope it will help the lazy users. :slightly_smiling_face:

**Comment by moy** [comment]
Thanks!
