### ISSUE TITLE
Formatting only diffed files

### ISSUE THREAD

**Issue by DerekCresswell** [Sarcasm/run-clang-format#21]
I saw in the readme that a goal was to be able to format only changed files. Here is a snippet :

```
import os
import subprocess

cmd = ['git', 'diff-index', '--name-only', 'HEAD']
output = subprocess.Popen(cmd, stdout=subprocess.PIPE).communicate()[0]
files = iter(output.splitlines())
```

You can then loop through this output to get each file.

It may not be the most elegant way but it does work. You can also check if there are changed files with `"git diff-index --quiet HEAD"`

I can supply a patch if this seems ok. : )

**Comment by Sarcasm** [comment]
Maybe this command is sufficient for your purpose?

    git clang-format --diff

**Comment by DerekCresswell** [comment]
I was going off the bottom of the readme. Have you implemented it with that method or not bothering with any? Perhaps I mis-read.

**Comment by Sarcasm** [comment]
Indeed the bottom of the README does not give enough details, TBH I don't remember what I had in mind...but `git clang-format --diff` does things, if one wants to just verify recently pushed commits in CI.

I'm closing since it looks like you aren't looking to solve an issue either, but were merely suggesting a way forward.
Thank you.
