### ISSUE TITLE
Seems like "clang-format --dry-run -Werror foo.cpp" basically already does exactly this?

### ISSUE THREAD

**Issue by rigtorp** [Sarcasm/run-clang-format#32]
Seems like "clang-format --dry-run -Werror foo.cpp" basically already does exactly this? 

Run clang-format in parallel:
```
$ find . -iname "*.cpp" -or -iname "*.h" | xargs -P0 -I{} clang-format --dry-run -Werror {}
```
If any file is not formatted:
```
$ echo $?
123
```

**Comment by Sarcasm** [comment]
It basically does this, except it doesn't?
Input arguments are different.
Output format is different.

How new is `--dry-run`? I'm pretty sure run-clang-format predates it.

Anyway, if you have the sufficient version, and like the output, by any mean use that! :)

Closing as I don't know what to do about this issue.

**Comment by rigtorp** [comment]
I just wanted to discuss the pros and cons. I've had run-clang-format recommended to me and it looks like a great solution. Previously I've done something like this but in CMake:

```bash
for FNAME in "*.cpp"
do
    clang-format $FNAME | diff - $FNAME
done
```

But it's quite slow on large codebases. With --dry-run you don't need to run diff, saving some CPU and IO.

There are some superficial differences between run-clang-format and using --dry-run. The interesting feature you have is the .clang-format-ignore file. 

--dry-run option was added in this commit: https://github.com/llvm/llvm-project/commit/6a1f7d6c9ff8228328d0e65b8678a9c6dff49837

Thank you for creating run-clang-format!

**Comment by Sarcasm** [comment]
Thank you for clarifying.
I think the idea behind run-clang-format.py is:
- to have a simple way to specify the input files to check (multiple files/directories, recursive descent of directories)
- a pretty output, readable in CI (assuming the code is mostly correctly formatted, and some changes might pass that aren't)
- do it reasonably fast
- be a self-contained script, just relying on clang-format and Python standard library, that can eventually be used on multiple OSes (although I only use Linux)

Initially, instead of a diff, I wanted to write errors like compiler warnings, which `--dry-run` seems to do.
But a diff seemed better, because it gives more context than just "this line is not correctly formatted".
