### ISSUE TITLE
Create package for pypi

### ISSUE THREAD

**Issue by robertsheehy-wf** [Sarcasm/run-clang-format#6]
This is an awesome tool and it'd be nice if this was a pip-installable from https://pypi.org/.

**Comment by rnestler** [comment]
That would be indeed awesome! @Sarcasm would you be interested in pull requests implementing that?

**Comment by Sarcasm** [comment]
Anything annoying with vendoring this file in your projects?
It should work the same as long as clang-format and python aren't updated in the project.
Did you ever miss an update?

For now, I feel like this will only be more maintenance work for me.
Need to have the tools setup, make official tag/release, test the install, etc.
Nothing insurmontable, but seeing the rates of change for the project, I will spend most of my time trying to remember these steps.

FWIW, since this issue has been created, there has been a single change merged, about a typo in the README.

**Comment by robertsheehy-wf** [comment]
> Anything annoying with vendoring this file in your projects?

Eh, ideally it's easier for developers if they don't have maintain their own copy of the script.

Overall sounds good though. I understand where you're coming from. Thanks!
